version: '3'

services:
  discovery:
    build: .
    image: discovery
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka/
    container_name: discovery
    ports:
      - "8761:8761"
#poi da rimuovere, serve a far comunicare diversi docker-compose in un network di default, ma kube dovrebbe già farlo
networks:
  default:
    external:
      name: front_default